uinv.iconUserConfig = {
  name: "点_fWfHdp",
  VERSION: 1,
  config: {
    totalSize: 1,
    size: 1,
    boundingBox: [1, 1, 1],
    场景类型: "地图",
    inheritScale: false,
    localPosition: [0, 0, 0],
    layout: [0, 0, 0],
    angles: [0, 0, 0],
    items: [
      {
        type: "Icon/Model",
        tag: "模型_pYm3",
        name: "模型",
        config: {
          url: "model/3837491689e5474aa7107b96e88266dc/gltf/",
          layout: ["Center", "Top", "Center"],
          pivotLayout: ["Center", "Bottom", "Center"],
          layoutOffset: [0, 0, 0],
          lockYAxis: false,
          playAnimation: true,
          animationName: "no",
          animationLoopType: "no",
          onlySelf: true,
          rotation: [0, 180, 0],
          scale: [14, 14, 14],
          style: {},
          userData: { SKIP_THEME: true },
          headline: {
            getMethod: "objectProperty",
            propertyPath: "name",
            height: 0.3,
            useSpriteMaterial: true,
            lockYAxis: false,
            fontColor: "#ffffff",
            textBgColor: "#16181a",
            roundRectRadius: 10,
            textBgOpacity: 80,
            layoutOffset: [0, 1, 0],
            keepSize: false,
            textSpacing: 60,
            lineSpacing: 40,
            paddingTop: 7,
            pivot: [0.5, 1],
          },
        },
        code: "Model",
      },
    ],
  },
  configUI: [],
  configUIpro: [
    {
      caption: "物体锚点位置",
      type: "multiselection",
      des: "layout",
      selections: [
        [
          { keyname: "左", key: 0 },
          { keyname: "中", key: 0.5 },
          { keyname: "右", key: 1 },
        ],
        [
          { keyname: "上", key: 0 },
          { keyname: "中", key: 0.5 },
          { keyname: "下", key: 1 },
        ],
        [
          { keyname: "前", key: 1 },
          { keyname: "中", key: 0.5 },
          { keyname: "后", key: 0 },
        ],
      ],
    },
    {
      caption: "偏移位置",
      type: "multinumber",
      number: 3,
      des: "localPosition",
      prefix: ["左右方向", "上下方向", "前后方向"],
      postfix: ["米", "米", "米"],
    },
    {
      caption: "旋转角度",
      type: "multinumber",
      number: 3,
      des: "angles",
      prefix: ["绕X轴", "绕Y轴", "绕Z轴"],
      postfix: ["度", "度", "度"],
      note: "仅类型选择固定轴向时生效",
    },
    { caption: "继承父级缩放", type: "bool", des: "inheritScale" },
  ],
};
